services:

  control_api:
    build:
      context: .
      dockerfile: dockerfile.control_api
    environment:
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_DB: scs-konverter
      POSTGRES_USER: postgres
      SQL_db_container: db-scs
      PORT_db: 5432
      JWT_SECRET: ${JWT_SECRET}
      ABLAUF_ZEIT_MIN: 300
    ports: 
     - "8000:8000"
  db-scs:
    image: postgres:17
    environment:
      POSTGRES_DB: scs-konverter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PW}

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
 postgres_data:

