FROM python:3.13 AS Builder

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev --no-install-project


#---------------------------------------

FROM python:3.13-slim

WORKDIR /app

RUN useradd --create-home appuser

COPY --from=Builder /app/.venv /app/.venv

COPY . .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8001

CMD ["/app/.venv/bin/uvicorn", "control_api:app", "--host", "0.0.0.0", "--port", "8000"]
